%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rosbag2-examples-py
Version:        0.32.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rosbag2_examples_py package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-example-interfaces
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-rosbag2-py
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-example-interfaces
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-rosbag2-py
BuildRequires:  ros-kilted-std-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
BuildRequires:  ros-kilted-ament-xmllint
%endif

%description
Python bag writing tutorial

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 geoff <gbiggs@killbots.net> - 0.32.0-2
- Autogenerated by Bloom

* Fri Apr 18 2025 geoff <gbiggs@killbots.net> - 0.32.0-1
- Autogenerated by Bloom

* Tue Feb 04 2025 geoff <gbiggs@killbots.net> - 0.31.0-1
- Autogenerated by Bloom

* Wed Sep 04 2024 geoff <gbiggs@killbots.net> - 0.29.0-1
- Autogenerated by Bloom

* Fri Jun 21 2024 geoff <gbiggs@killbots.net> - 0.28.0-1
- Autogenerated by Bloom

* Tue Apr 30 2024 geoff <gbiggs@killbots.net> - 0.27.0-1
- Autogenerated by Bloom

* Wed Apr 17 2024 geoff <gbiggs@killbots.net> - 0.26.1-1
- Autogenerated by Bloom

* Tue Apr 16 2024 geoff <gbiggs@killbots.net> - 0.26.0-1
- Autogenerated by Bloom

* Thu Mar 28 2024 geoff <gbiggs@killbots.net> - 0.25.0-1
- Autogenerated by Bloom

* Mon Mar 11 2024 geoff <gbiggs@killbots.net> - 0.24.0-3
- Autogenerated by Bloom

* Wed Mar 06 2024 geoff <gbiggs@killbots.net> - 0.24.0-2
- Autogenerated by Bloom

