%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-ros2bag
Version:        0.22.7
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros2bag package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-ament-index-python
Requires:       ros-iron-rclpy
Requires:       ros-iron-ros2cli
Requires:       ros-iron-rosbag2-py
Requires:       ros-iron-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-iron-ament-copyright
BuildRequires:  ros-iron-ament-flake8
BuildRequires:  ros-iron-ament-pep257
BuildRequires:  ros-iron-launch-testing
BuildRequires:  ros-iron-launch-testing-ros
BuildRequires:  ros-iron-rosbag2-storage-default-plugins
BuildRequires:  ros-iron-rosbag2-test-common
%endif

%description
Entry point for rosbag in ROS 2

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/iron"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Fri Jul 12 2024 Michael Orlov <michael.orlov@apex.ai> - 0.22.7-1
- Autogenerated by Bloom

* Thu Feb 08 2024 Michael Orlov <michael.orlov@apex.ai> - 0.22.6-1
- Autogenerated by Bloom

* Sat Nov 18 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.5-1
- Autogenerated by Bloom

* Wed Oct 25 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.4-1
- Autogenerated by Bloom

* Mon Sep 11 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.3-1
- Autogenerated by Bloom

* Fri Jul 14 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.2-1
- Autogenerated by Bloom

* Thu May 18 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.1-1
- Autogenerated by Bloom

* Thu Apr 20 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.0-2
- Autogenerated by Bloom

* Tue Apr 18 2023 Michael Orlov <michael.orlov@apex.ai> - 0.22.0-1
- Autogenerated by Bloom

* Thu Apr 13 2023 Michael Orlov <michael.orlov@apex.ai> - 0.21.0-2
- Autogenerated by Bloom

* Thu Apr 13 2023 Michael Orlov <michael.orlov@apex.ai> - 0.21.0-1
- Autogenerated by Bloom

* Tue Mar 21 2023 Michael Orlov <michael.orlov@apex.ai> - 0.20.0-2
- Autogenerated by Bloom

